FROM python:3.10-slim

WORKDIR /app

# Создаём директорию для логов
RUN mkdir -p /app/logs

# Устанавливаем системные зависимости
RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    git \
    && rm -rf /var/lib/apt/lists/*

# Копируем зависимости и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения
COPY . .

# Настройка кодировки
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

EXPOSE 5000
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
