"""change constraion for name in work_formats

Revision ID: 019a965005ae
Revises: 41558f912871
Create Date: 2025-07-03 22:16:50.888482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019a965005ae'
down_revision: Union[str, Sequence[str], None] = '41558f912871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='work_formats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('name'), 'work_formats', ['name'], unique=True)
    # ### end Alembic commands ###
