"""add vacancy_key_skills

Revision ID: 05770d51df06
Revises: ca2bfd1de4a9
Create Date: 2025-07-03 15:41:30.717793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05770d51df06'
down_revision: Union[str, Sequence[str], None] = 'ca2bfd1de4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_key_skills',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('key_skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['key_skill_id'], ['key_skills.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'key_skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_key_skills')
    # ### end Alembic commands ###
