"""add unique to experience, work_format, key_skill

Revision ID: 24766c782543
Revises: 5abd0938985a
Create Date: 2025-07-03 14:51:50.231146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24766c782543'
down_revision: Union[str, Sequence[str], None] = '5abd0938985a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'experience_levels', ['name'])
    op.create_unique_constraint(None, 'key_skills', ['name'])
    op.create_unique_constraint(None, 'work_formats', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_formats', type_='unique')
    op.drop_constraint(None, 'key_skills', type_='unique')
    op.drop_constraint(None, 'experience_levels', type_='unique')
    # ### end Alembic commands ###
