"""add employment_forms, working_hours, work_schedules tables

Revision ID: 287ae2806fa3
Revises: 2cb60e6b16a5
Create Date: 2025-07-04 20:44:35.648019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287ae2806fa3'
down_revision: Union[str, Sequence[str], None] = '2cb60e6b16a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_external', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_external')
    )
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_external', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_external')
    )
    op.create_table('working_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_external', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_external')
    )
    op.create_table('vacancy_work_schedules',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('work_schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.ForeignKeyConstraint(['work_schedule_id'], ['work_schedules.id'], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'work_schedule_id')
    )
    op.add_column('vacancies', sa.Column('employment_form_id', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('working_hours_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'employment_forms', ['employment_form_id'], ['id'])
    op.create_foreign_key(None, 'vacancies', 'working_hours', ['working_hours_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'working_hours_id')
    op.drop_column('vacancies', 'employment_form_id')
    op.drop_table('vacancy_work_schedules')
    op.drop_table('working_hours')
    op.drop_table('work_schedules')
    op.drop_table('employment_forms')
    # ### end Alembic commands ###
