"""add employer and industry tables

Revision ID: 2cb60e6b16a5
Revises: 019a965005ae
Create Date: 2025-07-04 16:40:23.574858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cb60e6b16a5'
down_revision: Union[str, Sequence[str], None] = '019a965005ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_external', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('accredited_it_employer', sa.Boolean(), nullable=True),
    sa.Column('open_vacancies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_external')
    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_external', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_external')
    )
    op.create_table('employer_industries',
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('employer_id', 'industry_id')
    )
    op.add_column('vacancies', sa.Column('employer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'employers', ['employer_id'], ['id'])
    op.drop_column('vacancies', 'employer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('employer', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'employer_id')
    op.drop_table('employer_industries')
    op.drop_table('industries')
    op.drop_table('employers')
    # ### end Alembic commands ###
