"""add id_external professional role

Revision ID: 41558f912871
Revises: 8899da14e093
Create Date: 2025-07-03 22:05:09.134332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41558f912871'
down_revision: Union[str, Sequence[str], None] = '8899da14e093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='experience_levels')
    op.add_column('professional_roles', sa.Column('id_external', sa.Integer(), nullable=False))
    op.drop_index(op.f('name'), table_name='professional_roles')
    op.create_unique_constraint(None, 'professional_roles', ['id_external'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professional_roles', type_='unique')
    op.create_index(op.f('name'), 'professional_roles', ['name'], unique=True)
    op.drop_column('professional_roles', 'id_external')
    op.create_index(op.f('name'), 'experience_levels', ['name'], unique=True)
    # ### end Alembic commands ###
