"""add is_active to salaries_history and key_skils_history tables

Revision ID: 425ac7d65cdc
Revises: f9a3be959dab
Create Date: 2025-07-16 20:18:24.999614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425ac7d65cdc'
down_revision: Union[str, Sequence[str], None] = 'f9a3be959dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_skill_history', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('salary_history', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_history', 'is_active')
    op.drop_column('key_skill_history', 'is_active')
    # ### end Alembic commands ###
