"""add salaries

Revision ID: 5abd0938985a
Revises: c9b91bca2d52
Create Date: 2025-07-02 23:10:41.554912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5abd0938985a'
down_revision: Union[str, Sequence[str], None] = 'c9b91bca2d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salary_from', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('salary_to', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id')
    )
    op.drop_table('vacancy_work_formats')
    op.drop_table('vacancy_key_skills')
    op.add_column('vacancies', sa.Column('status', sa.String(length=50), nullable=False))
    op.drop_column('vacancies', 'salary_from')
    op.drop_column('vacancies', 'salary_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('salary_to', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('vacancies', sa.Column('salary_from', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('vacancies', 'status')
    op.create_table('vacancy_key_skills',
    sa.Column('vacancy_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['key_skills.id'], name=op.f('vacancy_key_skills_ibfk_2')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('vacancy_key_skills_ibfk_1')),
    sa.PrimaryKeyConstraint('vacancy_id', 'skill_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vacancy_work_formats',
    sa.Column('vacancy_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_format_id', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('vacancy_work_formats_ibfk_1')),
    sa.ForeignKeyConstraint(['work_format_id'], ['work_formats.id'], name=op.f('vacancy_work_formats_ibfk_2')),
    sa.PrimaryKeyConstraint('vacancy_id', 'work_format_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('salaries')
    # ### end Alembic commands ###
