"""add professional role relation with vacancy

Revision ID: 8899da14e093
Revises: f8d7a293d672
Create Date: 2025-07-03 21:25:57.993796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8899da14e093'
down_revision: Union[str, Sequence[str], None] = 'f8d7a293d672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('professional_role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'professional_roles', ['professional_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'professional_role_id')
    # ### end Alembic commands ###
