"""rollback changed relation vacancy with search_queries

Revision ID: a30c46ab22cc
Revises: fa9ce907318a
Create Date: 2025-07-28 20:08:05.531402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a30c46ab22cc'
down_revision: Union[str, Sequence[str], None] = 'fa9ce907318a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_query_vacancies')
    op.add_column('vacancies', sa.Column('search_query_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'search_queries', ['search_query_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'search_query_id')
    op.create_table('search_query_vacancies',
    sa.Column('search_query_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vacancy_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], name=op.f('search_query_vacancies_ibfk_1')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('search_query_vacancies_ibfk_2')),
    sa.PrimaryKeyConstraint('search_query_id', 'vacancy_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
