"""add professional_role

Revision ID: c68717d6c3d9
Revises: 05770d51df06
Create Date: 2025-07-03 15:48:44.341984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68717d6c3d9'
down_revision: Union[str, Sequence[str], None] = '05770d51df06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_vacancies', sa.Column('professional_role', sa.String(length=255), nullable=True))
    op.add_column('temporary_vacancies', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporary_vacancies', 'created_at')
    op.drop_column('temporary_vacancies', 'professional_role')
    # ### end Alembic commands ###
