"""add vacancy_work_formats

Revision ID: ca2bfd1de4a9
Revises: 09908c52e22c
Create Date: 2025-07-03 15:39:20.179915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2bfd1de4a9'
down_revision: Union[str, Sequence[str], None] = '09908c52e22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_work_formats',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('work_format_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.ForeignKeyConstraint(['work_format_id'], ['work_formats.id'], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'work_format_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_work_formats')
    # ### end Alembic commands ###
