"""changed relation vacancy with search_queries

Revision ID: fa9ce907318a
Revises: 883ebb3a82b7
Create Date: 2025-07-28 19:46:58.003281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa9ce907318a'
down_revision: Union[str, Sequence[str], None] = '883ebb3a82b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_query_vacancies',
    sa.Column('search_query_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('search_query_id', 'vacancy_id')
    )
    op.drop_constraint(op.f('vacancies_ibfk_6'), 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'search_query_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('search_query_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vacancies_ibfk_6'), 'vacancies', 'search_queries', ['search_query_id'], ['id'])
    op.drop_table('search_query_vacancies')
    # ### end Alembic commands ###
