"""add mode to salary

Revision ID: ffedc99c23e3
Revises: 287ae2806fa3
Create Date: 2025-07-04 20:53:44.135633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffedc99c23e3'
down_revision: Union[str, Sequence[str], None] = '287ae2806fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salaries', sa.Column('mode_id', sa.String(length=50), nullable=True))
    op.add_column('salaries', sa.Column('mode_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salaries', 'mode_name')
    op.drop_column('salaries', 'mode_id')
    # ### end Alembic commands ###
